name: Concurrency
#on means when to trigger this pipeline we can trigger on push or manual or someother events  like ceating PR, updatingPR, creating branches, creationg issues
on: [push] #someone code push to this repostory trigger the code
concurrency: # this workflow should be trigger for any branch only once 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true #exsiting will be cancelled and latest will run 
jobs: #like pipeline one workflow can have multiple pipelines
  hello: #this is job name 
    runs-on: ubuntu-latest  # linux OS, we can have windows or MAC
    steps: #stages
    - name: step1
      run: sleep 20
     