name: Parallel
on: [push] #someone code push to this repostory trigger the code
jobs: #like pipeline one workflow can have multiple pipelines
  job-1: #these should be uniqic ,job-1 and job-4 are paraleel , no dependancey
    runs-on: ubuntu-latest  # linux OS, we can have windows or MAC
    steps: #stages
      - name: step1
        run: echo " hi, iam from job-1"
  job-2: 
    needs: job-1
    runs-on: ubuntu-latest  # linux OS, we can have windows or MAC
    steps: #stages
      - name: step1
        run: echo " hi, iam from job-2"

  job-3: 
    needs: job-2 #job-3 depends on job-2 
    runs-on: ubuntu-latest  # linux OS, we can have windows or MAC
    steps: #stages
      - name: step1
        run: echo " hi, iam from job-3"

  job-4:  
    runs-on: ubuntu-latest  # linux OS, we can have windows or MAC
    steps: #stages
      - name: step1
        run: echo " hi, iam from job-4"

     